services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['command']

    Atoolo\Search\Console\:
        resource: '../src/Console'

    atoolo_search.indexer.console.progress_bar:
      class:  'Atoolo\Search\Console\Command\Io\IndexerProgressBar'

    Atoolo\Search\Console\Command\Indexer:
      arguments:
        - '@atoolo_resource.resource_channel'
        - '@atoolo_search.indexer.console.progress_bar'
        - '@atoolo_search.indexer.indexer_collection'

    Atoolo\Search\Console\Command\IndexerInternalResourceUpdate:
      arguments:
        - '@atoolo_resource.resource_channel'
        - '@atoolo_search.indexer.console.progress_bar'
        - '@atoolo_search.indexer.internal_resource_indexer'

    Atoolo\Search\Console\Command\Search:
      arguments:
        - '@atoolo_resource.resource_channel'
        - '@atoolo_search.search'

    Atoolo\Search\Console\Command\Suggest:
      arguments:
        - '@atoolo_resource.resource_channel'
        - '@atoolo_search.suggest'

    Atoolo\Search\Console\Command\MoreLikeThis:
      arguments:
        - '@atoolo_resource.resource_channel'
        - '@atoolo_search.more_like_this'

    Atoolo\Search\Console\Command\DumpIndexDocument:
      arguments:
        - '@atoolo_resource.resource_channel'
        - '@atoolo_search.indexer.index_document_dumper'

    Atoolo\Search\Console\Application:
        public: true
        arguments:
            - !tagged_iterator command